name: Continuous Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Kubernetes
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml

      - name: Check deployment
        run: |
          kubectl get pods
          kubectl get services
